<?php
    /* @var Netopia\Netcard\Block\Redirect $block */
    $quote = $block->getQuote();
    $formData = $block->getFormData();
    $paymentUrl = ($block->getConfigData('api/is_live') == 1) ? 'https://secure.mobilpay.ro' : 'http://sandboxsecure.mobilpay.ro';
      
    if($formData['status']) {
       ?>
        <div class="">
            <img src="https://suport.mobilpay.ro/np-logo-blue.svg" width="134" alt="Netopia Payment>"/>
            <h1 class="">
                <span class="" >You will redirect to Netopia Website</span>
            </h1>
        </div>
        <form method="post" id="mobilpay-form" action="<?php echo $paymentUrl ?>">
            <input type="hidden" name="data" value="<?php echo $formData['data'] ?>"/>
            <input type="hidden" name="env_key" id="env_key" value="<?php echo $formData['form_key'] ?>"/>
        </form>

        <script>
            document.getElementById('mobilpay-form').submit();
        </script>
        <?php
    }else {
        echo '<div class="alert alert-danger" role="alert">
                OOPS, something is wrong, you are not able to redirect into Payment page!
              </div>';
              if(!is_null($formData['message'])) {
                echo '
                <div class="alert alert-danger" role="alert">
                    <h5>'.$formData['message'].'</h5>
                </div>
                ';
              }
    }

?>
