<?php
    /* @var Netopia\Netcard\Block\Redirect $block */
    $quote = $block->getQuote();
    $formData = $block->getFormData();
    $paymentUrl = ($block->getConfigData('mode/is_live')) ? 'https://secure.mobilpay.ro' : 'https://sandboxsecure.mobilpay.ro';

    if($formData['status']) {
       ?>
        <div class="">
            <img src="https://suport.mobilpay.ro/np-logo-blue.svg" width="134" alt="Netopia Payment>"/>
            <h1 class="">
                <span class="" >You will redirect to Netopia Website</span>
            </h1>
        </div>
        <form method="post" id="mobilpay-form" action="<?php echo $paymentUrl ?>">
            <input type="hidden" name="data" value="<?php echo $formData['data'] ?>"/>
            <input type="hidden" name="env_key" id="env_key" value="<?php echo $formData['form_key'] ?>"/>
            <!-- <button type="submit" class="button">SEND (Temporary - Test MODE)</button> -->
        </form>

        <script>
            document.getElementById('mobilpay-form').submit();
        </script>
        <?php
    }else {
        echo '<div class="alert alert-danger" role="alert">
                Something went wrong, please contact us!
              </div>';
    }

?>
