<?php /* @var Netopia\Netcard\Block\Success $block */ ?>
<?php 
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
    $orderData = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($block->getOrderId());
    switch ($orderData['status']) {
        case 'canceled':
            $msg = "Plata a fost anulata";
            break;
        case 'complete':
            $msg = "Plata a fost finalizata cu succes";
            break;
        case 'payment_review':
            $msg = "Plata este in curs de procesare";
            break;
        case 'processing':
            $msg = "Plata este in curs de procesare";
            break;
        case 'fraud':
            $msg = "Plata este anulata";
            break;                    
        default:
            $msg = "Plata este in ".$orderData['status'];
            break;
    }

?>
<div class="page-title-wrapper">
    <img src="https://suport.mobilpay.ro/np-logo-blue.svg" width="134" alt="Netopia Payment>"/>
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper"><?php echo $msg; ?></span>
    </h1>
</div>
<div class="checkout-success">
    <?php 
        if (!in_array($orderData['status'], array("canceled", "fraud"))) {
            ?>
            <p>Your order number : <strong><?php echo $block->getOrderId();?></strong></p>
            <p>Your total paid amount : <strong><?php echo $orderData->getData('base_grand_total');?></strong></p>
            <div class="actions-toolbar">
                <div class="primary">
                    <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
                </div>
            </div>
            <?php
        } elseif($orderData['status'] == "canceled") {
            ?>
            <div class="actions-toolbar">
                <div class="primary">
                    <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
                </div>
            </div>
            <?php
        }
    ?>
    
</div>
