<script>
require([
    'jquery',
    'prototype',
], function(jQuery){
    function self_validation() {
        params = {
        };

        new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
            loaderArea:     false,
            asynchronous:   true,
            parameters:     params,
            onSuccess: function(transport) {
                response = JSON.parse(transport.responseText);
                // console.log(transport);
                var resultText = '';
                    if (transport.status > 200) {
                        resultText = transport.statusText;
                    } else {
                        resultText = response.msg;
                    }
                    jQuery('#selfvalidation_message').text(resultText);
            }
        });
        // console.log(response);
    }

    jQuery('#selfvalidation_button').click(function () {
        self_validation ();
    });
});
</script>
<?php 
    // $controller = $block->getCustomUrl();
    echo $block->getButtonHtml();
?>
<span id="selfvalidation_message" style="padding-left: 10px; font-weight: bold;"></span>